name: Resourcepack Zipper

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # A non-shallow repository clone is required

      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest # Uses the latest PackSquash release supported by the action
          shader_source_transformation_strategy: keep_as_is

      - name: Create ZIP file
        run: |
          COMMIT_ID=$(git rev-parse --short HEAD)
          ZIP_NAME="ancient_debris_tex.zip"
          echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV
          zip -r "${ZIP_NAME}" .

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: resource-pack-artifact
          path: ${{ env.ZIP_NAME }}

      - name: Set current datetime as env variable
        env:
          TZ: "Asia/Tokyo" # タイムゾーン指定
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.RESOURCE_ZIPPER }}
        with:
          tag_name: release-${{ env.CURRENT_DATETIME }}-${{ github.sha }}
          name: Release ${{ env.CURRENT_DATETIME }} ${{ github.sha }}
          draft: false
          prerelease: false
          files: ${{ env.ZIP_NAME }}
